### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ssl1321ois**
Add tutorial feature, connect to AMS server, and fix Chinese input in Timelog.

### CODE REVIEW

**Comment by ssl1321ois** [comment]
logout button, stopwatch

**Review by ssl1321ois — COMMENTED** [review]
good

**Review by ssl1321ois — COMMENTED** [review]
code review

**Review by ssl1321ois — COMMENTED** [review]
code review

**Review by benny870704 — APPROVED** [review]

**Review by Nightlord851108 — APPROVED** [review]
Good enough

**Pull request merged**
